### PR TITLE
Dress Rehearsal Testnet "Spadina" v0.12.2

### PR DESCRIPTION
**Pull request by q9f**
Spadina v0.12.2 _dress rehearsal_ testnet (scheduled)

Depends on: https://github.com/ethereum/eth2.0-specs/issues/2052

### CODE REVIEW

**Comment by djrtwo** [comment]
I think we should lower `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT` to something very trivial to ensure that the testnet launches on that tuesday regardless of community engagement. That is, if just a small amount of validators want to have another go at a practice genesis, I don't think it should hold up the event in this case

Suggestion: `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1024`

**Comment by Bzh5579cc** [comment]
那個網站是中國人身份證而用的，我是香港的身分證，老說我的身份認不正確😱￼

**Comment by q9f** [comment]
> Suggestion: `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1024`

Done

**Review by djrtwo — APPROVED** [review]
Looks good!

Note that we will probably be "officially" at [`v0.12.3`](https://github.com/ethereum/eth2.0-specs/pull/2057) later this week, but won't affect anything here

**Comment by CarlBeek** [comment]
It would be useful to have a different `GENESIS_FORK_VERSION` to mainnet in this config. While slashings are prevented via `genesis_validators_root` deposits are not distinct between these two chains, thereby allowing users to deposit with the same keys (and proofs of possession).

In the Launchpad in particular, deposits are identified by the `GENESIS_FORK_VERSION` and as this PR currently stands, users could end up making the wrong deposit.

**Comment by rolfyone** [comment]
teku bootnode: 
`enr:-KG4QAxcrhmEz0t86EcxDpNcPpvNim8m9iG4zEkFxXWUm293cJ9HE_45DgXOcQyImsTt_6EYxpwCKMlGGF1aM037VoIChGV0aDKQ9aX9QgAAAAD__________4JpZIJ2NIJpcIQDFt-UiXNlY3AyNTZrMaECkR4C5DVO_9rB48eHTY4kdyOHsguTEDlvb7Ce0_mvghSDdGNwgiMog3VkcIIjKA`

**Review by djrtwo — APPROVED** [review]

**Pull request merged**
